// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkA6A9dY4Qa64LH-biJ4NrsceBw5xaDHA',
    appId: '1:847620738332:web:d10180f19bfe3287d7fed9',
    messagingSenderId: '847620738332',
    projectId: 'loginapp-10914',
    authDomain: 'loginapp-10914.firebaseapp.com',
    storageBucket: 'loginapp-10914.firebasestorage.app',
    measurementId: 'G-RRP2HEVF8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKeiwt_gmj82RNxMksIqqsCuSOOUX5mk',
    appId: '1:847620738332:android:f298267fcfda705cd7fed9',
    messagingSenderId: '847620738332',
    projectId: 'loginapp-10914',
    storageBucket: 'loginapp-10914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUx8JxFY7cFLgxrQDq32eRsuRnYpwxxg',
    appId: '1:847620738332:ios:99f57d648bd31c0cd7fed9',
    messagingSenderId: '847620738332',
    projectId: 'loginapp-10914',
    storageBucket: 'loginapp-10914.firebasestorage.app',
    iosBundleId: 'com.example.demoProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUx8JxFY7cFLgxrQDq32eRsuRnYpwxxg',
    appId: '1:847620738332:ios:99f57d648bd31c0cd7fed9',
    messagingSenderId: '847620738332',
    projectId: 'loginapp-10914',
    storageBucket: 'loginapp-10914.firebasestorage.app',
    iosBundleId: 'com.example.demoProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkA6A9dY4Qa64LH-biJ4NrsceBw5xaDHA',
    appId: '1:847620738332:web:97bd4fa647c4801ad7fed9',
    messagingSenderId: '847620738332',
    projectId: 'loginapp-10914',
    authDomain: 'loginapp-10914.firebaseapp.com',
    storageBucket: 'loginapp-10914.firebasestorage.app',
    measurementId: 'G-0MCHCBGY6R',
  );
}
